defaults:
 - _self_
 - trainer: default
 - model: default
 - data: default

 - data/splits: default
 - data/module: default

experiment_name: ${now:%Y-%m-%d}/${now:%H-%M-%S}
path: /scratch/kd24/${oc.env:USER}/ML/FourCastNeXt/Training/${experiment_name}

fit: False

hydra:
  verbose: false
  run:
    dir: ${path}