# Copyright Commonwealth of Australia, Bureau of Meteorology 2024.
# This software is provided under license 'as is', without warranty
# of any kind including, but not limited to, fitness for a particular
# purpose. The user assumes the entire risk as to the use and
# performance of the software. In no event shall the copyright holder
# be held liable for any claim, damages or other liability arising
# from the use of the software.

# ruff: noqa: F401 E402

"""
National Computing Infrastructure specific Indexes

| Name        | Description |
| :---        |       ----: |
| [ERA5][site_archive_nci.ERA5]                | ECWMF ReAnalysis v5       |
| [ACCESS][site_archive_nci.ACCESS]            | Australian Community Climate and Earth-System Simulator       |
| [AGCD][site_archive_nci.AGCD]                | Australian Gridded Climate Data        |
| [BRAN][site_archive_nci.BRAN]                | Bluelink ReANalysis        |
| [OceanMaps][site_archive_nci.OceanMaps]      | Ocean Modelling and Analysis Prediction System        |
| [MODIS][site_archive_nci.MODIS]              | MODerate resolution Imaging Spectroradiometer       |
| [Himawari][site_archive_nci.Himawari]        | Himawari 8/9 satellite data       |
| [BARRA][site_archive_nci.BARRA]              | Bureau of meteorology Atmospheric high-resolution Regional Reanalysis for Australia       |
| [BARPA][site_archive_nci.BARPA]              | Bureau of Meteorology Atmospheric Regional Projections for Australia       |
| [BARRA_V2][site_archive_nci.BARRA_V2]        | Bureau of meteorology Atmospheric high-resolution Regional Reanalysis for Australia v2    |
"""

import pyearthtools.data
from pyearthtools.data.archive import register_archive


ROOT_DIRECTORIES = {
    "ACCESS": "/g/data/wr45/ops_aps3/access-{region}/1/",
    "ACCESS_S": "/g/data/ux62/access-s2/{type}/",
    "AGCD": "/g/data/zv2/agcd/v1",
    "ERA5": "/g/data/rt52/era5/{level}-levels/{resolution}/",
    "Himawari": "/g/data/rv74/satellite-products/arc/der/himawari-ahi/solar/p1s/latest/",
    "BRAN": "/g/data/gb6/BRAN/BRAN2020/",
    "OceanMaps": "/g/data/rr6/OceanMAPS/",
    "MODIS": "/g/data/fj4/MODIS_LAI/{region}/nc/",
    "BARRA": "/g/data/cj37/BARRA/BARRA_{region}/{version}/{datatype}",
    "BARPA": "/g/data/py18/BARPA/",
    "BARRA_V2": "/g/data/ob53/BARRA2/",
}


register_archive("ROOT_DIRECTORIES")(ROOT_DIRECTORIES)

import site_archive_nci

from site_archive_nci.ACCESS import ACCESS
from site_archive_nci.AGCD import AGCD
from site_archive_nci.BRAN import BRAN
from site_archive_nci.BARRA import BARRA
from site_archive_nci.BARRAV2 import BARRA_V2
from site_archive_nci.BARPA import BARPA
from site_archive_nci.ERA5 import ERA5
from site_archive_nci.MODIS import MODIS
from site_archive_nci.OceanMaps import OceanMaps
from site_archive_nci.Himawari import Himawari

register_archive("NCI")(site_archive_nci)

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"
