# Copyright Commonwealth of Australia, Bureau of Meteorology 2024.
# This software is provided under license 'as is', without warranty
# of any kind including, but not limited to, fitness for a particular
# purpose. The user assumes the entire risk as to the use and
# performance of the software. In no event shall the copyright holder
# be held liable for any claim, damages or other liability arising
# from the use of the software.

# ruff: noqa: F401 E402

"""
National Computing Infrastructure specific Indexes

| Name        | Description |
| :---        |       ----: |
| [ERA5][edit_archive_NCI.ERA5]                | ECWMF ReAnalysis v5       |
| [ACCESS][edit_archive_NCI.ACCESS]            | Australian Community Climate and Earth-System Simulator       |
| [AGCD][edit_archive_NCI.AGCD]                | Australian Gridded Climate Data        |
| [BRAN][edit_archive_NCI.BRAN]                | Bluelink ReANalysis        |
| [OceanMaps][edit_archive_NCI.OceanMaps]      | Ocean Modelling and Analysis Prediction System        |
| [MODIS][edit_archive_NCI.MODIS]              | MODerate resolution Imaging Spectroradiometer       |
| [Himiwari][edit_archive_NCI.Himiwari]        | Himiwari 8/9 satellite data       |
| [BARRA][edit_archive_NCI.BARRA]              | Bureau of meteorology Atmospheric high-resolution Regional Reanalysis for Australia       |
| [BARPA][edit_archive_NCI.BARPA]              | Bureau of Meteorology Atmospheric Regional Projections for Australia       |
| [BARRA_V2][edit_archive_NCI.BARRA_V2]        | Bureau of meteorology Atmospheric high-resolution Regional Reanalysis for Australia v2    |
"""

import edit.data
from edit.data.archive import register_archive


ROOT_DIRECTORIES = {
    "ACCESS": "/g/data/wr45/ops_aps3/access-{region}/1/",
    "ACCESS_S": "/g/data/ux62/access-s2/{type}/",
    "AGCD": "/g/data/zv2/agcd/v1",
    "ERA5": "/g/data/rt52/era5/{level}-levels/{resolution}/",
    "HIMIWARI": "/g/data/rv74/satellite-products/arc/der/himawari-ahi/solar/p1s/latest/",
    "BRAN": "/g/data/gb6/BRAN/BRAN2020/",
    "OceanMaps": "/g/data/rr6/OceanMAPS/",
    "MODIS": "/g/data/fj4/MODIS_LAI/{region}/nc/",
    "BARRA": "/g/data/cj37/BARRA/BARRA_{region}/{version}/{datatype}",
    "BARPA": "/g/data/py18/BARPA/",
    "BARRA_V2": "/g/data/ob53/BARRA2/",
}


register_archive("ROOT_DIRECTORIES")(ROOT_DIRECTORIES)

import edit_archive_NCI

from edit_archive_NCI.ACCESS import ACCESS
from edit_archive_NCI.AGCD import AGCD
from edit_archive_NCI.BRAN import BRAN
from edit_archive_NCI.BARRA import BARRA
from edit_archive_NCI.BARRAV2 import BARRA_V2
from edit_archive_NCI.BARPA import BARPA
from edit_archive_NCI.ERA5 import ERA5
from edit_archive_NCI.MODIS import MODIS
from edit_archive_NCI.OceanMaps import OceanMaps
from edit_archive_NCI.Himiwari import Himiwari

register_archive("NCI")(edit_archive_NCI)

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"
