pipeline:
  run_parallel: False     # Attempt to run parallel at all, if False, will use Serial Interface

  parallel:               # Configuration for parallel running
    enabled:              # Which interfaces are enabled
      Delayed: True
      Futures: False

    dask:                 # Configuration for dask
      start: True
      client:             # Dask client config
        processes: False

      config: {}          # Dask config to be set after spinning up distributed cluster

    default: 'Serial'     # Default interface

  exceptions:             # Exception handling
    max_filter: 10        # Max filter exceptions before raising
    max_iterator: 20
    default_ignore: []    # Default exceptions to ignore when iterating

  repr:
    show_graph: True      # Show graph in ipython repr
